kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pubz-mysql-pvc
  labels:
    app: django
  annotations:
    "volume.beta.kubernetes.io/storage-class": "nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: pubz-mysql-pv
  
