apiVersion: v1
kind: PersistentVolume
metadata:
  name: pubz-pv-media
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs"
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.37
    path: /srv/nfsroot/k8s/pubz-media
